//

#include "angle.h"
#include "Camera.h"
#include "Light.h"
#include "Object.h"
#include "ObjLoader.h"
#include "MyOGL.h"
#include "MyShaders.h"
#include "MyVector3d.h"
#include "Texture.h"
#include "targetver.h"
#include "Resource.h"
#include "Render.h"
#include "Ray.h"
#include "Primitives.h"
#include "PrimitivesStatic.h"
#include "OpenGLrememberProj.h"
#include "GUItextRectangle.h"